apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app  # Matches the label of your pods
  ports:
    - protocol: TCP
      port: 80           # Service port (accessible within the cluster)
      targetPort: 3000   # Container's port
