name: ArgoCD Deployment

on:
  workflow_run:
    workflows: ["Docker Build and Push"]  # Trigger after the Docker build pipeline
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Run only if CI succeeded
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version
        id: version
        run: |
          CURRENT_VERSION=$(cat VERSION)
          echo "::set-output name=version::$CURRENT_VERSION"

      - name: Update Kubernetes manifests with new version
        run: |
          # Replace the image tag in your Kubernetes manifests
          sed -i "s|bharath415/node:.*|bharath415/node:${{ steps.version.outputs.version }}|g" deployment.yml

      - name: Commit updated manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yml
          git commit -m "Update image tag to ${{ steps.version.outputs.version }}"
          git push
