name: ArgoCD Deployment

on:
  workflow_run:
    workflows: ["Docker Build and Push"]  # Ensure this matches your CI workflow name
    types:
      - completed
  workflow_dispatch:  # Allow manual execution

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'  # Run on success or manual trigger

    steps:
      - name: Checkout ArgoCD manifests repo
        uses: actions/checkout@v4
        with:
          repository: your-org/your-argocd-repo  # Change to your ArgoCD repo
          ref: master  # Checkout master branch
          token: ${{ secrets.GH_PAT }}  # Ensure you have the correct token

      - name: Download VERSION file from CI
        uses: actions/download-artifact@v4
        with:
          name: version-file

      - name: Read version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Kubernetes manifests with new version
        run: |
          sed -i "s|bharath415/node:[0-9.]*|bharath415/node:${{ env.VERSION }}|g" deploy.yml

      - name: Commit updated manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master  # Ensure working on master branch
          git add deploy.yml svc.yml
          git commit -m "Update image tag to ${{ env.VERSION }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/your-org/your-argocd-repo.git HEAD:master
